
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmyipadder.h"

/*
* The configuration table for devices
*/

XMyipadder_Config XMyipadder_ConfigTable[XPAR_XMYIPADDER_NUM_INSTANCES] =
{
	{
		XPAR_MYIPADDER_0_DEVICE_ID,
		XPAR_MYIPADDER_0_S_AXI_BUS_A_BASEADDR
	}
};


