# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jules/.Xilinx/vitis_hls/2020.2.2/vitis_hls_examples/HLS-Tiny-Tutorials/interface_axi_lite/proj_axi_lite/solution1/impl/vhdl/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jules/.Xilinx/vitis_hls/2020.2.2/vitis_hls_examples/HLS-Tiny-Tutorials/interface_axi_lite/proj_axi_lite/solution1/impl/vhdl/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/myIPAdder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/jules/.Xilinx/vitis_hls/2020.2.2/vitis_hls_examples/HLS-Tiny-Tutorials/interface_axi_lite/proj_axi_lite/solution1/impl/vhdl/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jules/.Xilinx/vitis_hls/2020.2.2/vitis_hls_examples/HLS-Tiny-Tutorials/interface_axi_lite/proj_axi_lite/solution1/impl/vhdl/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/myIPAdder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
