# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/jules/.Xilinx/vitis_hls/2020.2.2/vitis_hls_examples/HLS-Tiny-Tutorials/interface_axi_lite/proj_axi_lite/solution1/impl/vhdl/myIPAdder.xdc

# Block Designs: bd/bd_0/bd_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0 || ORIG_REF_NAME==bd_0} -quiet] -quiet

# IP: bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0_hls_inst_0 || ORIG_REF_NAME==bd_0_hls_inst_0} -quiet] -quiet

# XDC: c:/Users/jules/.Xilinx/vitis_hls/2020.2.2/vitis_hls_examples/HLS-Tiny-Tutorials/interface_axi_lite/proj_axi_lite/solution1/impl/vhdl/project.gen/sources_1/bd/bd_0/bd_0_ooc.xdc
